language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.1"
  - "4.0"
  - "4.1"
sudo: false
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
